# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-12 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingDuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=255, unique=True)),
                ('arrived_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('start_time', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
    ]
